/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on ../board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for Woodchuck
*/

/*
    Board identifier
*/
#define BOARD_Woodchuck
#define BOARD_NAME                     "Woodchuck"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   0U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F072xB

/*
    IO pins assignments.
*/

#define GPIOA_PIN0                     0U
#define GPIOA_LED_RED                  1U
#define GPIOA_GPS_TX                   2U
#define GPIOA_GPS_RX                   3U
#define GPIOA_RADIO_TX_DATA            4U
#define GPIOA_LED_GREEN                5U
#define GPIOA_LED_BLUE                 6U
#define GPIOA_PIN7                     7U
#define GPIOA_PIN8                     8U
#define GPIOA_RADIO_EN_PIN             9U
#define GPIOA_USART_1_RX               10U
#define GPIOA_PIN11                    11U
#define GPIOA_PIN12                    12U
#define GPIOA_PIN13                    13U
#define GPIOA_PIN14                    14U
#define GPIOA_BARO_NCS                 15U

#define GPIOB_PIN0                     0U
#define GPIOB_PIN1                     1U
#define GPIOB_PIN2                     2U
#define GPIOB_BARO_CLK                 3U
#define GPIOB_BARO_MISO                4U
#define GPIOB_BARO_MOSI                5U
#define GPIOB_PIN6                     6U
#define GPIOB_PIN7                     7U
#define GPIOB_PIN8                     8U
#define GPIOB_PIN9                     9U
#define GPIOB_PIN10                    10U
#define GPIOB_PIN11                    11U
#define GPIOB_PIN12                    12U
#define GPIOB_RADIO_CHANNEL_LSB        13U
#define GPIOB_RADIO_CHANNEL_MSB        14U
#define GPIOB_PIN15                    15U

#define GPIOC_PIN0                     0U
#define GPIOC_PIN1                     1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_PIN4                     4U
#define GPIOC_PIN5                     5U
#define GPIOC_PIN6                     6U
#define GPIOC_PIN7                     7U
#define GPIOC_PIN8                     8U
#define GPIOC_PIN9                     9U
#define GPIOC_PIN10                    10U
#define GPIOC_PIN11                    11U
#define GPIOC_PIN12                    12U
#define GPIOC_PIN13                    13U
#define GPIOC_PIN14                    14U
#define GPIOC_PIN15                    15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOE_PIN0                     0U		
#define GPIOE_PIN1                     1U		
#define GPIOE_PIN2                     2U		
#define GPIOE_PIN3                     3U		
#define GPIOE_PIN4                     4U		
#define GPIOE_PIN5                     5U		
#define GPIOE_PIN6                     6U		
#define GPIOE_PIN7                     7U		
#define GPIOE_PIN8                     8U		
#define GPIOE_PIN9                     9U		
#define GPIOE_PIN10                    10U		
#define GPIOE_PIN11                    11U		
#define GPIOE_PIN12                    12U		
#define GPIOE_PIN13                    13U		
#define GPIOE_PIN14                    14U		
#define GPIOE_PIN15                    15U

#define GPIOF_PIN0                     0U
#define GPIOF_PIN1                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_PIN6                     6U
#define GPIOF_PIN7                     7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

/*
    IO lines assignments.
*/

#define LINE_BARO_CLK                  PAL_LINE(GPIOB, 3U)
#define LINE_BARO_MISO                 PAL_LINE(GPIOB, 4U)
#define LINE_BARO_MOSI                 PAL_LINE(GPIOB, 5U)
#define LINE_BARO_NCS                  PAL_LINE(GPIOA, 15U)
#define LINE_GPS_RX                    PAL_LINE(GPIOA, 3U)
#define LINE_GPS_TX                    PAL_LINE(GPIOA, 2U)
#define LINE_LED_BLUE                  PAL_LINE(GPIOA, 6U)
#define LINE_LED_GREEN                 PAL_LINE(GPIOA, 5U)
#define LINE_LED_RED                   PAL_LINE(GPIOA, 1U)
#define LINE_RADIO_CHANNEL_LSB         PAL_LINE(GPIOB, 13U)
#define LINE_RADIO_CHANNEL_MSB         PAL_LINE(GPIOB, 14U)
#define LINE_RADIO_EN_PIN              PAL_LINE(GPIOA, 9U)
#define LINE_RADIO_TX_DATA             PAL_LINE(GPIOA, 4U)
#define LINE_USART_1_RX                PAL_LINE(GPIOA, 10U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - PIN0                         (unused).
 * PA1  - LED_RED                      (output).
 * PA2  - GPS_TX                       (af1).
 * PA3  - GPS_RX                       (af1).
 * PA4  - RADIO_TX_DATA                (analog).
 * PA5  - LED_GREEN                    (output).
 * PA6  - LED_BLUE                     (output).
 * PA7  - PIN7                         (unused).
 * PA8  - PIN8                         (unused).
 * PA9  - RADIO_EN_PIN                 (af1).
 * PA10 - USART_1_RX                   (af1).
 * PA11 - PIN11                        (unused).
 * PA12 - PIN12                        (unused).
 * PA13 - PIN13                        (unused).
 * PA14 - PIN14                        (unused).
 * PA15 - BARO_NCS                     (af0).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_INPUT(GPIOA_PIN0) | \
                                        PIN_MODE_OUTPUT(GPIOA_LED_RED) | \
                                        PIN_MODE_ALTERNATE(GPIOA_GPS_TX) | \
                                        PIN_MODE_ALTERNATE(GPIOA_GPS_RX) | \
                                        PIN_MODE_ANALOG(GPIOA_RADIO_TX_DATA) | \
                                        PIN_MODE_OUTPUT(GPIOA_LED_GREEN) | \
                                        PIN_MODE_OUTPUT(GPIOA_LED_BLUE) | \
                                        PIN_MODE_INPUT(GPIOA_PIN7) | \
                                        PIN_MODE_INPUT(GPIOA_PIN8) | \
                                        PIN_MODE_ALTERNATE(GPIOA_RADIO_EN_PIN) | \
                                        PIN_MODE_ALTERNATE(GPIOA_USART_1_RX) | \
                                        PIN_MODE_INPUT(GPIOA_PIN11) | \
                                        PIN_MODE_INPUT(GPIOA_PIN12) | \
                                        PIN_MODE_INPUT(GPIOA_PIN13) | \
                                        PIN_MODE_INPUT(GPIOA_PIN14) | \
                                        PIN_MODE_ALTERNATE(GPIOA_BARO_NCS))
#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LED_RED) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_TX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RADIO_TX_DATA) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LED_GREEN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LED_BLUE) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RADIO_EN_PIN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_USART_1_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_BARO_NCS))
#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOA_LED_RED) | \
                                        PIN_OSPEED_HIGH(GPIOA_GPS_TX) | \
                                        PIN_OSPEED_HIGH(GPIOA_GPS_RX) | \
                                        PIN_OSPEED_HIGH(GPIOA_RADIO_TX_DATA) | \
                                        PIN_OSPEED_HIGH(GPIOA_LED_GREEN) | \
                                        PIN_OSPEED_HIGH(GPIOA_LED_BLUE) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOA_RADIO_EN_PIN) | \
                                        PIN_OSPEED_HIGH(GPIOA_USART_1_RX) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOA_BARO_NCS))
#define VAL_GPIOA_PUPDR                (PIN_PUPD_PULLUP(GPIOA_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOA_LED_RED) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_TX) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_RX) | \
                                        PIN_PUPD_PULLUP(GPIOA_RADIO_TX_DATA) | \
                                        PIN_PUPD_PULLUP(GPIOA_LED_GREEN) | \
                                        PIN_PUPD_PULLUP(GPIOA_LED_BLUE) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOA_RADIO_EN_PIN) | \
                                        PIN_PUPD_PULLUP(GPIOA_USART_1_RX) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOA_BARO_NCS))
#define VAL_GPIOA_ODR                  (PIN_OD_HIGH(GPIOA_PIN0) | \
                                        PIN_OD_HIGH(GPIOA_LED_RED) | \
                                        PIN_OD_HIGH(GPIOA_GPS_TX) | \
                                        PIN_OD_HIGH(GPIOA_GPS_RX) | \
                                        PIN_OD_HIGH(GPIOA_RADIO_TX_DATA) | \
                                        PIN_OD_HIGH(GPIOA_LED_GREEN) | \
                                        PIN_OD_HIGH(GPIOA_LED_BLUE) | \
                                        PIN_OD_HIGH(GPIOA_PIN7) | \
                                        PIN_OD_HIGH(GPIOA_PIN8) | \
                                        PIN_OD_HIGH(GPIOA_RADIO_EN_PIN) | \
                                        PIN_OD_HIGH(GPIOA_USART_1_RX) | \
                                        PIN_OD_HIGH(GPIOA_PIN11) | \
                                        PIN_OD_HIGH(GPIOA_PIN12) | \
                                        PIN_OD_HIGH(GPIOA_PIN13) | \
                                        PIN_OD_HIGH(GPIOA_PIN14) | \
                                        PIN_OD_HIGH(GPIOA_BARO_NCS))
#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LED_RED, 0U) | \
                                        PIN_AFIO_AF(GPIOA_GPS_TX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_GPS_RX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_RADIO_TX_DATA, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LED_GREEN, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LED_BLUE, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN7, 0U))
#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOA_RADIO_EN_PIN, 1U) | \
                                        PIN_AFIO_AF(GPIOA_USART_1_RX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOA_BARO_NCS, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - PIN0                         (unused).
 * PB1  - PIN1                         (unused).
 * PB2  - PIN2                         (unused).
 * PB3  - BARO_CLK                     (af0).
 * PB4  - BARO_MISO                    (af0).
 * PB5  - BARO_MOSI                    (af0).
 * PB6  - PIN6                         (unused).
 * PB7  - PIN7                         (unused).
 * PB8  - PIN8                         (unused).
 * PB9  - PIN9                         (unused).
 * PB10 - PIN10                        (unused).
 * PB11 - PIN11                        (unused).
 * PB12 - PIN12                        (unused).
 * PB13 - RADIO_CHANNEL_LSB            (output).
 * PB14 - RADIO_CHANNEL_MSB            (output).
 * PB15 - PIN15                        (unused).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_INPUT(GPIOB_PIN0) | \
                                        PIN_MODE_INPUT(GPIOB_PIN1) | \
                                        PIN_MODE_INPUT(GPIOB_PIN2) | \
                                        PIN_MODE_ALTERNATE(GPIOB_BARO_CLK) | \
                                        PIN_MODE_ALTERNATE(GPIOB_BARO_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOB_BARO_MOSI) | \
                                        PIN_MODE_INPUT(GPIOB_PIN6) | \
                                        PIN_MODE_INPUT(GPIOB_PIN7) | \
                                        PIN_MODE_INPUT(GPIOB_PIN8) | \
                                        PIN_MODE_INPUT(GPIOB_PIN9) | \
                                        PIN_MODE_INPUT(GPIOB_PIN10) | \
                                        PIN_MODE_INPUT(GPIOB_PIN11) | \
                                        PIN_MODE_INPUT(GPIOB_PIN12) | \
                                        PIN_MODE_OUTPUT(GPIOB_RADIO_CHANNEL_LSB) | \
                                        PIN_MODE_OUTPUT(GPIOB_RADIO_CHANNEL_MSB) | \
                                        PIN_MODE_INPUT(GPIOB_PIN15))
#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BARO_CLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BARO_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BARO_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_RADIO_CHANNEL_LSB) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_RADIO_CHANNEL_MSB) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN15))
#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOB_BARO_CLK) | \
                                        PIN_OSPEED_HIGH(GPIOB_BARO_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOB_BARO_MOSI) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOB_RADIO_CHANNEL_LSB) | \
                                        PIN_OSPEED_HIGH(GPIOB_RADIO_CHANNEL_MSB) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN15))
#define VAL_GPIOB_PUPDR                (PIN_PUPD_PULLUP(GPIOB_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOB_BARO_CLK) | \
                                        PIN_PUPD_PULLUP(GPIOB_BARO_MISO) | \
                                        PIN_PUPD_PULLUP(GPIOB_BARO_MOSI) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOB_RADIO_CHANNEL_LSB) | \
                                        PIN_PUPD_PULLUP(GPIOB_RADIO_CHANNEL_MSB) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN15))
#define VAL_GPIOB_ODR                  (PIN_OD_HIGH(GPIOB_PIN0) | \
                                        PIN_OD_HIGH(GPIOB_PIN1) | \
                                        PIN_OD_HIGH(GPIOB_PIN2) | \
                                        PIN_OD_HIGH(GPIOB_BARO_CLK) | \
                                        PIN_OD_HIGH(GPIOB_BARO_MISO) | \
                                        PIN_OD_HIGH(GPIOB_BARO_MOSI) | \
                                        PIN_OD_HIGH(GPIOB_PIN6) | \
                                        PIN_OD_HIGH(GPIOB_PIN7) | \
                                        PIN_OD_HIGH(GPIOB_PIN8) | \
                                        PIN_OD_HIGH(GPIOB_PIN9) | \
                                        PIN_OD_HIGH(GPIOB_PIN10) | \
                                        PIN_OD_HIGH(GPIOB_PIN11) | \
                                        PIN_OD_HIGH(GPIOB_PIN12) | \
                                        PIN_OD_HIGH(GPIOB_RADIO_CHANNEL_LSB) | \
                                        PIN_OD_HIGH(GPIOB_RADIO_CHANNEL_MSB) | \
                                        PIN_OD_HIGH(GPIOB_PIN15))
#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BARO_CLK, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BARO_MISO, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BARO_MOSI, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN7, 0U))
#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOB_RADIO_CHANNEL_LSB, 0U) | \
                                        PIN_AFIO_AF(GPIOB_RADIO_CHANNEL_MSB, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN15, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - PIN0                         (unused).
 * PC1  - PIN1                         (unused).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - PIN4                         (unused).
 * PC5  - PIN5                         (unused).
 * PC6  - PIN6                         (unused).
 * PC7  - PIN7                         (unused).
 * PC8  - PIN8                         (unused).
 * PC9  - PIN9                         (unused).
 * PC10 - PIN10                        (unused).
 * PC11 - PIN11                        (unused).
 * PC12 - PIN12                        (unused).
 * PC13 - PIN13                        (unused).
 * PC14 - PIN14                        (unused).
 * PC15 - PIN15                        (unused).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_INPUT(GPIOC_PIN0) | \
                                        PIN_MODE_INPUT(GPIOC_PIN1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_INPUT(GPIOC_PIN4) | \
                                        PIN_MODE_INPUT(GPIOC_PIN5) | \
                                        PIN_MODE_INPUT(GPIOC_PIN6) | \
                                        PIN_MODE_INPUT(GPIOC_PIN7) | \
                                        PIN_MODE_INPUT(GPIOC_PIN8) | \
                                        PIN_MODE_INPUT(GPIOC_PIN9) | \
                                        PIN_MODE_INPUT(GPIOC_PIN10) | \
                                        PIN_MODE_INPUT(GPIOC_PIN11) | \
                                        PIN_MODE_INPUT(GPIOC_PIN12) | \
                                        PIN_MODE_INPUT(GPIOC_PIN13) | \
                                        PIN_MODE_INPUT(GPIOC_PIN14) | \
                                        PIN_MODE_INPUT(GPIOC_PIN15))
#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN15))
#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN15))
#define VAL_GPIOC_PUPDR                (PIN_PUPD_PULLUP(GPIOC_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN15))
#define VAL_GPIOC_ODR                  (PIN_OD_HIGH(GPIOC_PIN0) | \
                                        PIN_OD_HIGH(GPIOC_PIN1) | \
                                        PIN_OD_HIGH(GPIOC_PIN2) | \
                                        PIN_OD_HIGH(GPIOC_PIN3) | \
                                        PIN_OD_HIGH(GPIOC_PIN4) | \
                                        PIN_OD_HIGH(GPIOC_PIN5) | \
                                        PIN_OD_HIGH(GPIOC_PIN6) | \
                                        PIN_OD_HIGH(GPIOC_PIN7) | \
                                        PIN_OD_HIGH(GPIOC_PIN8) | \
                                        PIN_OD_HIGH(GPIOC_PIN9) | \
                                        PIN_OD_HIGH(GPIOC_PIN10) | \
                                        PIN_OD_HIGH(GPIOC_PIN11) | \
                                        PIN_OD_HIGH(GPIOC_PIN12) | \
                                        PIN_OD_HIGH(GPIOC_PIN13) | \
                                        PIN_OD_HIGH(GPIOC_PIN14) | \
                                        PIN_OD_HIGH(GPIOC_PIN15))
#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN7, 0U))
#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN15, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))
#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))
#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLUP(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN15))
#define VAL_GPIOD_ODR                  (PIN_OD_HIGH(GPIOD_PIN0) | \
                                        PIN_OD_HIGH(GPIOD_PIN1) | \
                                        PIN_OD_HIGH(GPIOD_PIN2) | \
                                        PIN_OD_HIGH(GPIOD_PIN3) | \
                                        PIN_OD_HIGH(GPIOD_PIN4) | \
                                        PIN_OD_HIGH(GPIOD_PIN5) | \
                                        PIN_OD_HIGH(GPIOD_PIN6) | \
                                        PIN_OD_HIGH(GPIOD_PIN7) | \
                                        PIN_OD_HIGH(GPIOD_PIN8) | \
                                        PIN_OD_HIGH(GPIOD_PIN9) | \
                                        PIN_OD_HIGH(GPIOD_PIN10) | \
                                        PIN_OD_HIGH(GPIOD_PIN11) | \
                                        PIN_OD_HIGH(GPIOD_PIN12) | \
                                        PIN_OD_HIGH(GPIOD_PIN13) | \
                                        PIN_OD_HIGH(GPIOD_PIN14) | \
                                        PIN_OD_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))
#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOE setup:
 *
 * PE0  - PIN0                         (unused).
 * PE1  - PIN1                         (unused).
 * PE2  - PIN2                         (unused).
 * PE3  - PIN3                         (unused).
 * PE4  - PIN4                         (unused).
 * PE5  - PIN5                         (unused).
 * PE6  - PIN6                         (unused).
 * PE7  - PIN7                         (unused).
 * PE8  - PIN8                         (unused).
 * PE9  - PIN9                         (unused).
 * PE10 - PIN10                        (unused).
 * PE11 - PIN11                        (unused).
 * PE12 - PIN12                        (unused).
 * PE13 - PIN13                        (unused).
 * PE14 - PIN14                        (unused).
 * PE15 - PIN15                        (unused).
*/
#define VAL_GPIOE_MODER                (PIN_MODE_INPUT(GPIOE_PIN0) | \
                                        PIN_MODE_INPUT(GPIOE_PIN1) | \
                                        PIN_MODE_INPUT(GPIOE_PIN2) | \
                                        PIN_MODE_INPUT(GPIOE_PIN3) | \
                                        PIN_MODE_INPUT(GPIOE_PIN4) | \
                                        PIN_MODE_INPUT(GPIOE_PIN5) | \
                                        PIN_MODE_INPUT(GPIOE_PIN6) | \
                                        PIN_MODE_INPUT(GPIOE_PIN7) | \
                                        PIN_MODE_INPUT(GPIOE_PIN8) | \
                                        PIN_MODE_INPUT(GPIOE_PIN9) | \
                                        PIN_MODE_INPUT(GPIOE_PIN10) | \
                                        PIN_MODE_INPUT(GPIOE_PIN11) | \
                                        PIN_MODE_INPUT(GPIOE_PIN12) | \
                                        PIN_MODE_INPUT(GPIOE_PIN13) | \
                                        PIN_MODE_INPUT(GPIOE_PIN14) | \
                                        PIN_MODE_INPUT(GPIOE_PIN15))
#define VAL_GPIOE_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOE_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN15))
#define VAL_GPIOE_OSPEEDR              (PIN_OSPEED_HIGH(GPIOE_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN15))
#define VAL_GPIOE_PUPDR                (PIN_PUPD_PULLUP(GPIOE_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN15))
#define VAL_GPIOE_ODR                  (PIN_OD_HIGH(GPIOE_PIN0) | \
                                        PIN_OD_HIGH(GPIOE_PIN1) | \
                                        PIN_OD_HIGH(GPIOE_PIN2) | \
                                        PIN_OD_HIGH(GPIOE_PIN3) | \
                                        PIN_OD_HIGH(GPIOE_PIN4) | \
                                        PIN_OD_HIGH(GPIOE_PIN5) | \
                                        PIN_OD_HIGH(GPIOE_PIN6) | \
                                        PIN_OD_HIGH(GPIOE_PIN7) | \
                                        PIN_OD_HIGH(GPIOE_PIN8) | \
                                        PIN_OD_HIGH(GPIOE_PIN9) | \
                                        PIN_OD_HIGH(GPIOE_PIN10) | \
                                        PIN_OD_HIGH(GPIOE_PIN11) | \
                                        PIN_OD_HIGH(GPIOE_PIN12) | \
                                        PIN_OD_HIGH(GPIOE_PIN13) | \
                                        PIN_OD_HIGH(GPIOE_PIN14) | \
                                        PIN_OD_HIGH(GPIOE_PIN15))
#define VAL_GPIOE_AFRL                 (PIN_AFIO_AF(GPIOE_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN7, 0U))
#define VAL_GPIOE_AFRH                 (PIN_AFIO_AF(GPIOE_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN14, 0U) | \
										PIN_AFIO_AF(GPIOE_PIN15, 0U))
										
/*
 *  GPIOF setup:
 *
 * PF0  - PIN0                         (unused).
 * PF1  - PIN1                         (unused).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - PIN6                         (unused).
 * PF7  - PIN7                         (unused).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_INPUT(GPIOF_PIN0) | \
                                        PIN_MODE_INPUT(GPIOF_PIN1) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_PIN6) | \
                                        PIN_MODE_INPUT(GPIOF_PIN7) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))
#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))
#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_PUPDR                (PIN_PUPD_PULLUP(GPIOF_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN15))
#define VAL_GPIOF_ODR                  (PIN_OD_HIGH(GPIOF_PIN0) | \
                                        PIN_OD_HIGH(GPIOF_PIN1) | \
                                        PIN_OD_HIGH(GPIOF_PIN2) | \
                                        PIN_OD_HIGH(GPIOF_PIN3) | \
                                        PIN_OD_HIGH(GPIOF_PIN4) | \
                                        PIN_OD_HIGH(GPIOF_PIN5) | \
                                        PIN_OD_HIGH(GPIOF_PIN6) | \
                                        PIN_OD_HIGH(GPIOF_PIN7) | \
                                        PIN_OD_HIGH(GPIOF_PIN8) | \
                                        PIN_OD_HIGH(GPIOF_PIN9) | \
                                        PIN_OD_HIGH(GPIOF_PIN10) | \
                                        PIN_OD_HIGH(GPIOF_PIN11) | \
                                        PIN_OD_HIGH(GPIOF_PIN12) | \
                                        PIN_OD_HIGH(GPIOF_PIN13) | \
                                        PIN_OD_HIGH(GPIOF_PIN14) | \
                                        PIN_OD_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN7, 0U))
#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
